name: mobile
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  shared_preferences: ^2.5.3
  device_preview: ^1.3.1
  provider: ^6.1.5+1
  flutter_screenutil: ^5.9.3
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  dio_cookie_manager: ^3.3.0
  cookie_jar: ^4.0.8
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.11.1
  build_runner: ^2.10.1

flutter:
  uses-material-design: true
